-- CONSTRUCTION OF THE BRONZE LAYER
	
-- ANALYSE OF SOURCE SYSTEMS
/* BUSINESS CONTEXT & OWNERSHIP
		WHO OWNS THE DATA?
		WHAT BUSINESS PROCESS IT SUPPORTS?
		SYSTEM AND DATA DOCUMENTATION
		DATA MODEL AND DATA CATALOG

	ARCHITECTURE & TECHNOLOGY STACK
		HOW IS DATA STORED? (SQL SERVER, ORACLE, AWS, AZURE...)
		WHAT ARE THE INTEGRATION CAPABILITIES? (API, KAFKA, FILE EXTRACT, DIRECT DB....)

	EXTRACT & LOAD
		INCREMENTAL VS FULL LOAD?
		DATA SCOPE & HISTORICAL NEEDS
		WHAT IS THE EXPECTED SIZE OF THE EXTRACT
		ARE THERE ANY DATA  VOLUME LIMITATIONS?
		HOW TO AVOID IMPACTING THE SOURCE SYSTEM PERFORMANCE
		ANY AUTHENTICATION ADN AUTHORIZATION? (TOKENS, SSH KEYS, VPN, IP WHITELISTING,...)
*/

--DATA INGESTION 
	-- CREATION OF DDL FOR TABLES

USE DATAWAREHOUSE;

--CREATION OF TABLES FOR FILES IN THE 'SOURCE_CRM' FOLDER
/* ALWAYS GOOD TO HAVE A 'CHECK', WHERE WE SEE IF THE TABLE ALREADY EXIST IN OUR DATABASE, TO AVOID ERRORS.
ALSO ALLOWS FOR A SEAMLESS METHOD TO ADD COLUMNS IN THE FUTURE IF NEEDED.*/

IF OBJECT_ID ('BRONZE.CRM_CUST_INFO', 'U') IS NOT NULL
	DROP TABLE BRONZE.CRM_CUST_INFO; 
CREATE TABLE BRONZE.CRM_CUST_INFO(
cst_id INT,
cst_key NVARCHAR(50),
cst_firstname NVARCHAR(50),
cst_lastname NVARCHAR(50),
cst_marital_status NVARCHAR(50),
cst_gndr NVARCHAR(50),
cst_create_date DATE
);
IF OBJECT_ID ('BRONZE.CRM_PRD_INFO', 'U') IS NOT NULL
	DROP TABLE BRONZE.CRM_PRD_INFO;
CREATE TABLE BRONZE.CRM_PRD_INFO(
prd_id INT,
prd_key NVARCHAR (50),
prd_nm NVARCHAR(50),
prd_cost INT,
prd_line NVARCHAR(50),
prd_start_dt DATETIME,
prd_end_dt DATETIME
);
IF OBJECT_ID ('BRONZE.CRM_SALES_DETAILS', 'U') IS NOT NULL
	DROP TABLE BRONZE.CRM_SALES_DETAILS;
CREATE TABLE BRONZE.CRM_SALES_DETAILS(
sls_ord_num NVARCHAR(50),
sls_prd_key NVARCHAR(50),
sls_cust_id INT,
sls_order_dt INT,
sls_ship_dt INT,
sls_due_dt INT,
sls_sales INT,
sls_quantity INT,
sls_price INT
);

--CREATION OF TABLES FOR FILES IN THE 'SOURCE_ERP' FOLDER
IF OBJECT_ID ('BRONZE.ERP_CUST_AZ12', 'U') IS NOT NULL
	DROP TABLE BRONZE.ERP_CUST_AZ12;
CREATE TABLE BRONZE.ERP_CUST_AZ12(
CID NVARCHAR(50),
BDATE DATE,
GEN NVARCHAR(50)
);

IF OBJECT_ID ('BRONZE.ERP_LOC_A101', 'U') IS NOT NULL
	DROP TABLE BRONZE.ERP_LOC_A101;
CREATE TABLE BRONZE.ERP_LOC_A101(
CID NVARCHAR(50),
CNTRY NVARCHAR(50)
);

IF OBJECT_ID ('BRONZE.ERP_PX_CAT_G1V2', 'U') IS NOT NULL
	DROP TABLE BRONZE.ERP_PX_CAT_G1V2;
CREATE TABLE BRONZE.ERP_PX_CAT_G1V2(
ID NVARCHAR(50),
CAT NVARCHAR(50),
SUBCAT NVARCHAR(50),
MAINTENANCE NVARCHAR(50)
);


