/* CREATION OF DATABASE, 'DATAWAREHOUSE'
---
SCRIPT PURPOSE:
  THIS SCRIPT CREATES A NEW DATABASE, 'DATAWAREHOUSE'. THE INITAL PART OF THE SCRIPT CHECKS IF THE DATABASES IS ALREADY EXISTING, AND IF SO, DROPS IT AND RECREATES IT.
  ALSO, THREE SCHEMAS ARE CREATED: BRONZE, SILVER AND GOLD. THIS REFELCTS THE THREE LAYER ARCHITECTURE:
          Bronze:
          Raw data landing zone 
          
          Silver: 
          Transformation and data cleansing 
          
          Gold:
          Build objects // Business ready objects 
----
WARNING:
  RUNNING THIS SCRIPT WILL DROP THE ENTIRE 'DATAWAREHOUSE' DATABASE, IF IT EXITS. THIS INCLUDES ALL DATA. PROCEED WITH CAUTION
  AND ENSURE YOU HAVE THE PROPER BACKUPS BEFORE RUNNING THIS SCRIPT.
*/

--ENSURES THE 'MASTER' IS UTILIZED, TO CREATE A NEW DATABASE
USE MASTER;

--DROP AND RECREATE THE 'DATAWAREHOUSE' DATABASE
-- ENSURES YOU ARE RECREATING THE DATABASES, PREVENTING ERRORS WHEN CREATING THE DATABASE AND SCHEMAS
IF EXISTS (SELECT 1 FROM sys.databases where name = 'DATAWAREHOUSE')
  BEGIN
    ALTER DATABASE DATAWAREHOUSE SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE DATAWAREHOUSE;
END;
GO

--CREATION OF NEW DATABASE, 'DATAWAREHOUSE'
CREATE DATABASE DATAWAREHOUSE
GO
-- SWITCH FROM 'MASTER' TO 'DATAWAREHOUSE'
USE DATAWAREHOUSE;
GO

--CREATION OF THE THREE SCHEMA LAYERS 
CREATE SCHEMA BRONZE;
GO
CREATE SCHEMA SILVER;
GO
CREATE SCHEMA GOLD;
GO
